name: Deploy Private Resources Hub app to S3 and CloudFront

on:
  workflow_dispatch:
    workflow_run:
      workflows: ["CI"]
      branches: ["main"]
      types:
        - completed

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  S3_BUCKET: private-resources-hub-dev-frontend
  CLOUDFRONT_DISTRIBUTION_ID: ENOAVYZNASEIR

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/private-resources-hub-dev-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync dist folder to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} \
            --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"